/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bananacounter;

/**
 *
 * @author Jason
 */
public class GUI extends javax.swing.JFrame
{

    /**
     * Creates new form GUI
     */
    public GUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jBnEatUp = new javax.swing.JButton();
        jBnEatDown = new javax.swing.JButton();
        jBnCntDown = new javax.swing.JButton();
        jBnCntUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBnCnt = new javax.swing.JTextField();
        jBnEat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banana Counter");
        setResizable(false);

        jBnEatUp.setText("+");
        jBnEatUp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBnEatUpActionPerformed(evt);
            }
        });

        jBnEatDown.setText("-");
        jBnEatDown.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBnEatDownActionPerformed(evt);
            }
        });

        jBnCntDown.setText("-");
        jBnCntDown.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBnCntDownActionPerformed(evt);
            }
        });

        jBnCntUp.setText("+");
        jBnCntUp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBnCntUpActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("/");

        jBnCnt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jBnCnt.setText("0");

        jBnEat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jBnEat.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jBnEatDown, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBnEatUp, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBnEat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBnCnt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBnCntUp, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBnCntDown, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnEatUp)
                    .addComponent(jBnEatDown)
                    .addComponent(jBnCntDown)
                    .addComponent(jBnCntUp)
                    .addComponent(jLabel1)
                    .addComponent(jBnCnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnEat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnEatDownActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBnEatDownActionPerformed
    {//GEN-HEADEREND:event_jBnEatDownActionPerformed
        bananEat = Integer.parseInt(jBnEat.getText());
        bananEat--;
        jBnEat.setText(Integer.toString(bananEat));
    }//GEN-LAST:event_jBnEatDownActionPerformed

    private void jBnEatUpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBnEatUpActionPerformed
    {//GEN-HEADEREND:event_jBnEatUpActionPerformed
        bananEat = Integer.parseInt(jBnEat.getText());
        bananEat++;
        jBnEat.setText(Integer.toString(bananEat));
    }//GEN-LAST:event_jBnEatUpActionPerformed

    private void jBnCntUpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBnCntUpActionPerformed
    {//GEN-HEADEREND:event_jBnCntUpActionPerformed
        bananCnt = Integer.parseInt(jBnCnt.getText());
        bananCnt++;
        jBnCnt.setText(Integer.toString(bananCnt));
    }//GEN-LAST:event_jBnCntUpActionPerformed

    private void jBnCntDownActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBnCntDownActionPerformed
    {//GEN-HEADEREND:event_jBnCntDownActionPerformed
        bananCnt = Integer.parseInt(jBnCnt.getText());
        bananCnt--;
        jBnCnt.setText(Integer.toString(bananCnt));
    }//GEN-LAST:event_jBnCntDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
            }
        });
    }
    private int bananEat;
    private int bananCnt;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBnCnt;
    private javax.swing.JButton jBnCntDown;
    private javax.swing.JButton jBnCntUp;
    private javax.swing.JTextField jBnEat;
    private javax.swing.JButton jBnEatDown;
    private javax.swing.JButton jBnEatUp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
